### ISSUE TITLE
Return first argument for non-getter functions

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/remotebmi#22]
In heat.jl and wflow.jl the non-getter functions return the first arg.

**Comment by sverhoeven** [comment]
Asked for conformation at https://github.com/csdms/bmi-example-julia/issues/8

**Comment by BSchilperoort** [comment]
the conclusion is that these functions (model control functions) shouldn't return anything, except for initialize.

In the Julia BMI implementation, `initialize` takes the model _type_, and returns the model struct.

**Comment by sverhoeven** [comment]
Ok, this is the current mode. 

As https://github.com/eWaterCycle/remotebmi/blob/b0aa7e74e0e324308ee566270f864e8bd87d735a/RemoteBMI.jl/src/Server.jl#L102-L115 we ignore any return by a model.
